apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name
  annotations:
    config.kubernetes.io/local-config: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
replacements:
- source:
    kind: WorkloadCluster
    name: workload-cluster
    fieldPath: spec.clusterName
  targets:
  - select:
      kind: Backup
    fieldPaths:
    - metadata.name
    options:
      delimiter: '-'
      index: 0
- source:
    kind: WorkloadCluster
    name: workload-cluster
    fieldPath: spec.backupStorageLocation
  targets:
  - select:
      kind: Backup
    fieldPaths:
    - spec.storageLocation
    options:
      delimiter: '-'
      index: 0
