apiVersion: apps/v1
kind: Deployment
metadata:
  name: ack-ec2-controller
  namespace: ack-system
  labels:
    app.kubernetes.io/name: ack-ec2-controller
    app.kubernetes.io/part-of: ack-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ack-ec2-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ack-ec2-controller
    spec:
      containers:
      - command:
        - ./bin/controller
        args:
        - --aws-region
        - "$(AWS_REGION)"
        - --aws-endpoint-url
        - "$(AWS_ENDPOINT_URL)"
        - --enable-development-logging=$(ACK_ENABLE_DEVELOPMENT_LOGGING)
        - --log-level
        - "$(ACK_LOG_LEVEL)"
        - --resource-tags
        - "$(ACK_RESOURCE_TAGS)"

        - --enable-leader-election=$(ENABLE_LEADER_ELECTION)
        - --leader-election-namespace
        - "$(LEADER_ELECTION_NAMESPACE)"
        - --reconcile-default-max-concurrent-syncs
        - "$(RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS)"
        image: public.ecr.aws/aws-controllers-k8s/ec2-controller:1.2.7
        name: controller
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: ACK_SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: AWS_ENDPOINT_URL
          value: "https://ec2.ap-northeast-2.amazonaws.com"
        - name: ACK_WATCH_NAMESPACE
          value: "ack-system"
        - name: ACK_ENABLE_DEVELOPMENT_LOGGING
          value: "false"
        - name: ACK_LOG_LEVEL
          value: "info"
        - name: ACK_RESOURCE_TAGS
          value: "services.k8s.aws/controller-version=%CONTROLLER_SERVICE%-%CONTROLLER_VERSION%,services.k8s.aws/namespace=%K8S_NAMESPACE%"
        - name: ENABLE_LEADER_ELECTION
          value: "false"
        - name: LEADER_ELECTION_NAMESPACE
          value: "ack-system"
        - name: RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS
          value: "60"
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        - name: AWS_SESSION_TOKEN
          value: ""
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      serviceAccountName: ack-ec2-controller
      hostIPC: false
      hostPID: false
      hostNetwork: false
      dnsPolicy: ClusterFirst
