apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: example
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.3.101
    port: 6443
  noCloudProvider: true
