apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: example-control-plane
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: example-control-plane
      image:
        checksum: ab54897a1bcae83581512cdeeda787f009846cfd7a63b298e472c1bd6c522d23
        checksumType: sha256
        format: qcow2
        url: http://192.168.3.99/k8s_v1.29/UBUNTU_9_NODE_IMAGE_K8S_v1.29.qcow2
