apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: catalog-workloads-oai-ran
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: main
    directory: /workloads/oai
    repo: https://github.com/vitu1234/catalog.git
  type: git


