apiVersion: ec2.services.k8s.aws/v1alpha1
kind: RouteTable
metadata:
  name: infra-aws-public-route-table
spec:
  vpcRef:
    from:
      name: infra-aws-vpc
  routes:
  - destinationCIDRBlock: 0.0.0.0/0
    gatewayRef:
      from:
        name: infra-aws-igw