apiVersion: ec2.services.k8s.aws/v1alpha1
kind: Subnet
metadata:
  name: infra-aws-private-subnet1
spec:
  availabilityZone: ap-northeast-2a
  cidrBlock: 10.0.128.0/20
  vpcRef:
    from:
      name: infra-aws-vpc
  routeTableRefs:
  - from:
      name: infra-aws-private-route-table