apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: vpc-cudu-f1
spec:
  topology: nephio
  routingTables:
  - name: vpc-cudu-f1
    prefixes:
    - prefix: 10:5::/32
      labels:
        nephio.org/network-name: f1
    - prefix: 10.100.50.244/24
      labels:
        nephio.org/network-name: f1
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-cudu-f1 
  bridgeDomains: 
  - name: vpc-cudu-f1
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: none
