apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata:
  name: vpc-cu-e1
spec:
  topology: nephio
  routingTables:
  - name: vpc-cu-e1
    prefixes:
    - prefix: 10:4::/32
      labels:
        nephio.org/network-name: e1
    - prefix: 10.200.50.0/24
      labels:
        nephio.org/network-name: e1
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-cu-e1 
  bridgeDomains: 
  - name: vpc-cu-e1
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: none
