apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-system
spec:
  interval: 1m
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
  valuesFrom:
  - kind: ConfigMap
    name: minio-values
    valuesKey: values.yaml
