apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-example-n3
  namespace: cuup-example
spec:
  config: '{ "cniVersion": "0.3.1", "type": "ipvlan", "capabilities": { "ips": true }, "master": "ens5", "mode": "l3", "ipam": { "type": "static" } }'
